// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* ah.h
   Generated by wsdl2h 2.8.55 from http://10.44.4.209:20622/soa/autentificaHuella/autentificaHuella?wsdl and typemap.dat
   2019-06-07 22:03:24 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on ah.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c++,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   aos:autentificaHuella/autentificaHuella.wsdl                             *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "aos:autentificaHuella/autentificaHuella.wsdl"
ns2 = "http://tempuri.org/aos.xsd"
ns3 = "aos:autentificaHuella"

*/

#define SOAP_NAMESPACE_OF_ns2	"http://tempuri.org/aos.xsd"
//gsoap ns2   schema namespace:	http://tempuri.org/aos.xsd
//gsoap ns2   schema form:	unqualified

#define SOAP_NAMESPACE_OF_ns3	"aos:autentificaHuella"
//gsoap ns3   schema namespace:	aos:autentificaHuella
//gsoap ns3   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


//  Forward declaration of class ns3__entrada.
class ns3__entrada;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://tempuri.org/aos.xsd                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   aos:autentificaHuella                                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://tempuri.org/aos.xsd                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   aos:autentificaHuella                                                    *
 *                                                                            *
\******************************************************************************/

/// @brief "aos:autentificaHuella":entrada is a complexType.
///
/// class ns3__entrada operations:
/// - ns3__entrada* soap_new_ns3__entrada(soap*) allocate and default initialize
/// - ns3__entrada* soap_new_ns3__entrada(soap*, int num) allocate array and default initialize values
/// - ns3__entrada* soap_new_req_ns3__entrada(soap*, ...) allocate, set required members
/// - ns3__entrada* soap_new_set_ns3__entrada(soap*, ...) allocate, set all public members
/// - ns3__entrada::soap_default(soap*) default initialize members
/// - int soap_read_ns3__entrada(soap*, ns3__entrada*) deserialize from a stream
/// - int soap_write_ns3__entrada(soap*, ns3__entrada*) serialize to a stream
/// - ns3__entrada* ns3__entrada::soap_dup(soap*) returns deep copy of ns3__entrada, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - ns3__entrada::soap_del() deep deletes ns3__entrada data members, use only after ns3__entrada::soap_dup(NULL) (use soapcpp2 -Ed)
class ns3__entrada
{ public:
/// Element "idu-num" of XSD type xs:string.
    char*                                idu_num                        1;	///< Required element.
/// Element "des-Template64" of XSD type xs:string.
    char*                                des_Template64                 1;	///< Required element.
/// Element "num-nivel" of XSD type xs:string.
    char*                                num_nivel                      1;	///< Required element.
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://tempuri.org/aos.xsd                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://tempuri.org/aos.xsd                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   aos:autentificaHuella                                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   aos:autentificaHuella                                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns3  service name:	autentificaHuella 
//gsoap ns3  service type:	autentificaHuellaPortType 
//gsoap ns3  service port:	http://10.44.4.209:20622/soa/autentificaHuella/autentificaHuella.cgi 
//gsoap ns3  service namespace:	aos:autentificaHuella 
//gsoap ns3  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage autentificaHuella Definitions

@section autentificaHuella_bindings Service Bindings

  - @ref autentificaHuella

@section autentificaHuella_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page autentificaHuella Binding "autentificaHuella"

@section autentificaHuella_service Service Documentation "autentificaHuella"
gSOAP 2.8.12 generated service definition

@section autentificaHuella_operations Operations of Binding "autentificaHuella"

  - @ref ns3__ConsultaCliente

  - @ref ns3__ConsultaEmpleado

  - @ref ns3__Cliente

  - @ref ns3__Empleado

@section autentificaHuella_ports Default endpoints of Binding "autentificaHuella"

  - http://10.44.4.209:20622/soa/autentificaHuella/autentificaHuella.cgi

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   autentificaHuella                                                        *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns3__ConsultaCliente                                                     *
 *                                                                            *
\******************************************************************************/


/** Operation "ns3__ConsultaCliente" of service binding "autentificaHuella".
Service definition of function autentificaHuella__ConsultaCliente

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - Default endpoints:
    - http://10.44.4.209:20622/soa/autentificaHuella/autentificaHuella.cgi

  - Default SOAP action or REST location path:
    - "ConsultaCliente"

  - Addressing input action: "ConsultaCliente"

  - Addressing output action: "ConsultaClienteResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns3__ConsultaCliente(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns3__entrada*                       entradaCliente,
    // output parameters:
    char*                              &num_respuesta
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns3__ConsultaCliente(
    struct soap *soap,
    // input parameters:
    ns3__entrada*                       entradaCliente,
    // output parameters:
    char*                              &num_respuesta
  );
@endcode

C++ proxy class (defined in soapautentificaHuellaProxy.h generated with soapcpp2):
@code
  class autentificaHuellaProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapautentificaHuellaService.h generated with soapcpp2):
@code
  class autentificaHuellaService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns3  service method-protocol:	ConsultaCliente SOAP
//gsoap ns3  service method-style:	ConsultaCliente rpc
//gsoap ns3  service method-encoding:	ConsultaCliente http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns3  service method-input-action:	ConsultaCliente ConsultaCliente
//gsoap ns3  service method-output-action:	ConsultaCliente ConsultaClienteResponse
int ns3__ConsultaCliente(
    ns3__entrada*                       :entradaCliente,	///< Input parameter, : unqualified name as per RPC encoding
    char*                              &:num_respuesta	///< Output parameter, : unqualified name as per RPC encoding
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns3__ConsultaEmpleado                                                    *
 *                                                                            *
\******************************************************************************/


/** Operation "ns3__ConsultaEmpleado" of service binding "autentificaHuella".
Service definition of function autentificaHuella__ConsultaEmpleado

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - Default endpoints:
    - http://10.44.4.209:20622/soa/autentificaHuella/autentificaHuella.cgi

  - Default SOAP action or REST location path:
    - "ConsultaEmpleado"

  - Addressing input action: "ConsultaEmpleado"

  - Addressing output action: "ConsultaEmpleadoResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns3__ConsultaEmpleado(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns3__entrada*                       entradaEmpleado,
    // output parameters:
    char*                              &num_respuesta
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns3__ConsultaEmpleado(
    struct soap *soap,
    // input parameters:
    ns3__entrada*                       entradaEmpleado,
    // output parameters:
    char*                              &num_respuesta
  );
@endcode

C++ proxy class (defined in soapautentificaHuellaProxy.h generated with soapcpp2):
@code
  class autentificaHuellaProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapautentificaHuellaService.h generated with soapcpp2):
@code
  class autentificaHuellaService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns3  service method-protocol:	ConsultaEmpleado SOAP
//gsoap ns3  service method-style:	ConsultaEmpleado rpc
//gsoap ns3  service method-encoding:	ConsultaEmpleado http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns3  service method-input-action:	ConsultaEmpleado ConsultaEmpleado
//gsoap ns3  service method-output-action:	ConsultaEmpleado ConsultaEmpleadoResponse
int ns3__ConsultaEmpleado(
    ns3__entrada*                       :entradaEmpleado,	///< Input parameter, : unqualified name as per RPC encoding
    char*                              &:num_respuesta	///< Output parameter, : unqualified name as per RPC encoding
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns3__Cliente                                                             *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns3__ClienteResponse" of operation "ns3__Cliente".
struct ns3__ClienteResponse
{
    char*                               :num_respuesta;	///< Output parameter, : unqualified name as per RPC encoding
    char*                               :num_adicional;	///< Output parameter, : unqualified name as per RPC encoding
    char*                               :num_dedo;	///< Output parameter, : unqualified name as per RPC encoding
    char*                               :fec_actualizacion;	///< Output parameter, : unqualified name as per RPC encoding
};

/** Operation "ns3__Cliente" of service binding "autentificaHuella".
Service definition of function autentificaHuella__Cliente

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - Default endpoints:
    - http://10.44.4.209:20622/soa/autentificaHuella/autentificaHuella.cgi

  - Default SOAP action or REST location path:
    - "Cliente"

  - Addressing input action: "Cliente"

  - Addressing output action: "ClienteResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns3__Cliente(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns3__entrada*                       entradaCliente,
    // output parameters:
    struct ns3__ClienteResponse&
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns3__Cliente(
    struct soap *soap,
    // input parameters:
    ns3__entrada*                       entradaCliente,
    // output parameters:
    struct ns3__ClienteResponse&
  );
@endcode

C++ proxy class (defined in soapautentificaHuellaProxy.h generated with soapcpp2):
@code
  class autentificaHuellaProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapautentificaHuellaService.h generated with soapcpp2):
@code
  class autentificaHuellaService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns3  service method-protocol:	Cliente SOAP
//gsoap ns3  service method-style:	Cliente rpc
//gsoap ns3  service method-encoding:	Cliente http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns3  service method-input-action:	Cliente Cliente
//gsoap ns3  service method-output-action:	Cliente ClienteResponse
int ns3__Cliente(
    ns3__entrada*                       :entradaCliente,	///< Input parameter, : unqualified name as per RPC encoding
    struct ns3__ClienteResponse        &	///< Output response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns3__Empleado                                                            *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns3__EmpleadoResponse" of operation "ns3__Empleado".
struct ns3__EmpleadoResponse
{
    char*                               :num_respuesta;	///< Output parameter, : unqualified name as per RPC encoding
    char*                               :num_adicional;	///< Output parameter, : unqualified name as per RPC encoding
    char*                               :num_dedo;	///< Output parameter, : unqualified name as per RPC encoding
    char*                               :fec_actualizacion;	///< Output parameter, : unqualified name as per RPC encoding
};

/** Operation "ns3__Empleado" of service binding "autentificaHuella".
Service definition of function autentificaHuella__Empleado

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - Default endpoints:
    - http://10.44.4.209:20622/soa/autentificaHuella/autentificaHuella.cgi

  - Default SOAP action or REST location path:
    - "Empleado"

  - Addressing input action: "Empleado"

  - Addressing output action: "EmpleadoResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns3__Empleado(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns3__entrada*                       entradaEmpleado,
    // output parameters:
    struct ns3__EmpleadoResponse&
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns3__Empleado(
    struct soap *soap,
    // input parameters:
    ns3__entrada*                       entradaEmpleado,
    // output parameters:
    struct ns3__EmpleadoResponse&
  );
@endcode

C++ proxy class (defined in soapautentificaHuellaProxy.h generated with soapcpp2):
@code
  class autentificaHuellaProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapautentificaHuellaService.h generated with soapcpp2):
@code
  class autentificaHuellaService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns3  service method-protocol:	Empleado SOAP
//gsoap ns3  service method-style:	Empleado rpc
//gsoap ns3  service method-encoding:	Empleado http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns3  service method-input-action:	Empleado Empleado
//gsoap ns3  service method-output-action:	Empleado EmpleadoResponse
int ns3__Empleado(
    ns3__entrada*                       :entradaEmpleado,	///< Input parameter, : unqualified name as per RPC encoding
    struct ns3__EmpleadoResponse       &	///< Output response struct parameter
);

/**

@page autentificaHuella Binding "autentificaHuella"

@section autentificaHuella_policy_enablers Policy Enablers of Binding "autentificaHuella"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns2 Top-level root elements of schema "http://tempuri.org/aos.xsd"

@section ns3 Top-level root elements of schema "aos:autentificaHuella"

*/

/* End of ah.h */
