/* soapEcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy.cpp
   Generated by gSOAP 2.8.55 for ah.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapEcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy.h"

EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy() : soap(SOAP_IO_DEFAULT)
{	EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(const EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy& rhs)
{	soap_copy_context(this, &rhs);
	this->soap_endpoint = rhs.soap_endpoint;
}

EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(const struct soap &_soap) : soap(_soap)
{ }

EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(const char *endpoint) : soap(SOAP_IO_DEFAULT)
{	EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = endpoint;
}

EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(soap_mode iomode) : soap(iomode)
{	EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy_init(iomode, iomode);
}

EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(const char *endpoint, soap_mode iomode) : soap(iomode)
{	EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy_init(iomode, iomode);
	soap_endpoint = endpoint;
}

EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(soap_mode imode, soap_mode omode) : soap(imode, omode)
{	EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy_init(imode, omode);
}

EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::~EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy()
{
	this->destroy();
	}

void EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
        {"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"ns2", "aos:autentificaHuella", NULL, NULL},
        {"ns3", "http://coppel.com/ecommerce/ValidacionDeCorreosArg", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this, namespaces);
}

EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy *EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::copy()
{	EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy *dup = SOAP_NEW_COPY(EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(*(struct soap*)this));
	return dup;
}

EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy& EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::operator=(const EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy& rhs)
{	soap_copy_context(this, &rhs);
	this->soap_endpoint = rhs.soap_endpoint;
	return *this;
}

void EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::reset()
{	this->destroy();
	soap_done(this);
	soap_initialize(this);
	EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::soap_noheader()
{	this->header = NULL;
}

::SOAP_ENV__Header *EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::soap_header()
{	return this->header;
}

::SOAP_ENV__Fault *EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::soap_fault()
{	return this->fault;
}

const char *EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::validaSintaxisCorreo(const char *endpoint, const char *soap_action, ns3__validaSintaxisCorreoRequest *ns3__validaSintaxisCorreoRequest_, ns3__validaSintaxisCorreoResponse &ns3__validaSintaxisCorreoResponse_)
{	struct soap *soap = this;
	struct __ns3__validaSintaxisCorreo soap_tmp___ns3__validaSintaxisCorreo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:ValidaSintaxisCorreo";
	soap_tmp___ns3__validaSintaxisCorreo.ns3__validaSintaxisCorreoRequest_ = ns3__validaSintaxisCorreoRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__validaSintaxisCorreo(soap, &soap_tmp___ns3__validaSintaxisCorreo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__validaSintaxisCorreo(soap, &soap_tmp___ns3__validaSintaxisCorreo, "-ns3:validaSintaxisCorreo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__validaSintaxisCorreo(soap, &soap_tmp___ns3__validaSintaxisCorreo, "-ns3:validaSintaxisCorreo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__validaSintaxisCorreoResponse*>(&ns3__validaSintaxisCorreoResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__validaSintaxisCorreoResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__validaSintaxisCorreoResponse_.soap_get(soap, "ns3:validaSintaxisCorreoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::consultaCorreo(const char *endpoint, const char *soap_action, ns3__consultaCorreoRequest *ns3__consultaCorreoRequest_, ns3__consultaCorreoResponse &ns3__consultaCorreoResponse_)
{	struct soap *soap = this;
	struct __ns3__consultaCorreo soap_tmp___ns3__consultaCorreo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:ConsultaCorreo";
	soap_tmp___ns3__consultaCorreo.ns3__consultaCorreoRequest_ = ns3__consultaCorreoRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__consultaCorreo(soap, &soap_tmp___ns3__consultaCorreo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__consultaCorreo(soap, &soap_tmp___ns3__consultaCorreo, "-ns3:consultaCorreo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__consultaCorreo(soap, &soap_tmp___ns3__consultaCorreo, "-ns3:consultaCorreo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__consultaCorreoResponse*>(&ns3__consultaCorreoResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__consultaCorreoResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__consultaCorreoResponse_.soap_get(soap, "ns3:consultaCorreoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::validaCandidato(const char *endpoint, const char *soap_action, ns3__validaCandidatoRequest *ns3__validaCandidatoRequest_, ns3__validaCandidatoResponse &ns3__validaCandidatoResponse_)
{	struct soap *soap = this;
	struct __ns3__validaCandidato soap_tmp___ns3__validaCandidato;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:ValidaCandidato";
	soap_tmp___ns3__validaCandidato.ns3__validaCandidatoRequest_ = ns3__validaCandidatoRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__validaCandidato(soap, &soap_tmp___ns3__validaCandidato);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__validaCandidato(soap, &soap_tmp___ns3__validaCandidato, "-ns3:validaCandidato", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__validaCandidato(soap, &soap_tmp___ns3__validaCandidato, "-ns3:validaCandidato", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__validaCandidatoResponse*>(&ns3__validaCandidatoResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__validaCandidatoResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__validaCandidatoResponse_.soap_get(soap, "ns3:validaCandidatoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::validarFrecuencia(const char *endpoint, const char *soap_action, ns3__validarFrecuenciaRequest *ns3__validarFrecuenciaRequest_, ns3__validarFrecuenciaResponse &ns3__validarFrecuenciaResponse_)
{	struct soap *soap = this;
	struct __ns3__validarFrecuencia soap_tmp___ns3__validarFrecuencia;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:validarFrecuencia";
	soap_tmp___ns3__validarFrecuencia.ns3__validarFrecuenciaRequest_ = ns3__validarFrecuenciaRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__validarFrecuencia(soap, &soap_tmp___ns3__validarFrecuencia);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__validarFrecuencia(soap, &soap_tmp___ns3__validarFrecuencia, "-ns3:validarFrecuencia", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__validarFrecuencia(soap, &soap_tmp___ns3__validarFrecuencia, "-ns3:validarFrecuencia", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__validarFrecuenciaResponse*>(&ns3__validarFrecuenciaResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__validarFrecuenciaResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__validarFrecuenciaResponse_.soap_get(soap, "ns3:validarFrecuenciaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::desligueClienteCorreo(const char *endpoint, const char *soap_action, ns3__desligueClienteCorreoRequest *ns3__desligueClienteCorreoRequest_, ns3__desliqueClienteCorreoResponse &ns3__desliqueClienteCorreoResponse_)
{	struct soap *soap = this;
	struct __ns3__desligueClienteCorreo soap_tmp___ns3__desligueClienteCorreo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:desligueClienteCorreo";
	soap_tmp___ns3__desligueClienteCorreo.ns3__desligueClienteCorreoRequest_ = ns3__desligueClienteCorreoRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__desligueClienteCorreo(soap, &soap_tmp___ns3__desligueClienteCorreo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__desligueClienteCorreo(soap, &soap_tmp___ns3__desligueClienteCorreo, "-ns3:desligueClienteCorreo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__desligueClienteCorreo(soap, &soap_tmp___ns3__desligueClienteCorreo, "-ns3:desligueClienteCorreo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__desliqueClienteCorreoResponse*>(&ns3__desliqueClienteCorreoResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__desliqueClienteCorreoResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__desliqueClienteCorreoResponse_.soap_get(soap, "ns3:desliqueClienteCorreoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::desligueClienteNumeroCliente(const char *endpoint, const char *soap_action, ns3__desligueClienteNumeroClienteRequest *ns3__desligueClienteNumeroClienteRequest_, ns3__desliqueClienteNumeroClienteResponse &ns3__desliqueClienteNumeroClienteResponse_)
{	struct soap *soap = this;
	struct __ns3__desligueClienteNumeroCliente soap_tmp___ns3__desligueClienteNumeroCliente;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:desligueClienteNumeroCliente";
	soap_tmp___ns3__desligueClienteNumeroCliente.ns3__desligueClienteNumeroClienteRequest_ = ns3__desligueClienteNumeroClienteRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__desligueClienteNumeroCliente(soap, &soap_tmp___ns3__desligueClienteNumeroCliente);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__desligueClienteNumeroCliente(soap, &soap_tmp___ns3__desligueClienteNumeroCliente, "-ns3:desligueClienteNumeroCliente", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__desligueClienteNumeroCliente(soap, &soap_tmp___ns3__desligueClienteNumeroCliente, "-ns3:desligueClienteNumeroCliente", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__desliqueClienteNumeroClienteResponse*>(&ns3__desliqueClienteNumeroClienteResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__desliqueClienteNumeroClienteResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__desliqueClienteNumeroClienteResponse_.soap_get(soap, "ns3:desliqueClienteNumeroClienteResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::registroCorreo(const char *endpoint, const char *soap_action, ns3__registroCorreoRequest *ns3__registroCorreoRequest_, ns3__registroCorreoResponse &ns3__registroCorreoResponse_)
{	struct soap *soap = this;
	struct __ns3__registroCorreo soap_tmp___ns3__registroCorreo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:RegistroCorreo";
	soap_tmp___ns3__registroCorreo.ns3__registroCorreoRequest_ = ns3__registroCorreoRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__registroCorreo(soap, &soap_tmp___ns3__registroCorreo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__registroCorreo(soap, &soap_tmp___ns3__registroCorreo, "-ns3:registroCorreo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__registroCorreo(soap, &soap_tmp___ns3__registroCorreo, "-ns3:registroCorreo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__registroCorreoResponse*>(&ns3__registroCorreoResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__registroCorreoResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__registroCorreoResponse_.soap_get(soap, "ns3:registroCorreoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::registroCorreoBancoppel(const char *endpoint, const char *soap_action, ns3__registroCorreoBancoppelRequest *ns3__registroCorreoBancoppelRequest_, ns3__registroCorreoBancoppelResponse &ns3__registroCorreoBancoppelResponse_)
{	struct soap *soap = this;
	struct __ns3__registroCorreoBancoppel soap_tmp___ns3__registroCorreoBancoppel;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:RegistroCorreoBancoppel";
	soap_tmp___ns3__registroCorreoBancoppel.ns3__registroCorreoBancoppelRequest_ = ns3__registroCorreoBancoppelRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__registroCorreoBancoppel(soap, &soap_tmp___ns3__registroCorreoBancoppel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__registroCorreoBancoppel(soap, &soap_tmp___ns3__registroCorreoBancoppel, "-ns3:registroCorreoBancoppel", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__registroCorreoBancoppel(soap, &soap_tmp___ns3__registroCorreoBancoppel, "-ns3:registroCorreoBancoppel", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__registroCorreoBancoppelResponse*>(&ns3__registroCorreoBancoppelResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__registroCorreoBancoppelResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__registroCorreoBancoppelResponse_.soap_get(soap, "ns3:registroCorreoBancoppelResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::bloqueEstadistica(const char *endpoint, const char *soap_action, ns3__bloqueEstadisticaRequest *ns3__bloqueEstadisticaRequest_, ns3__bloqueEstadisticaResponse &ns3__bloqueEstadisticaResponse_)
{	struct soap *soap = this;
	struct __ns3__bloqueEstadistica soap_tmp___ns3__bloqueEstadistica;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:BloqueEstadistica";
	soap_tmp___ns3__bloqueEstadistica.ns3__bloqueEstadisticaRequest_ = ns3__bloqueEstadisticaRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__bloqueEstadistica(soap, &soap_tmp___ns3__bloqueEstadistica);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__bloqueEstadistica(soap, &soap_tmp___ns3__bloqueEstadistica, "-ns3:bloqueEstadistica", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__bloqueEstadistica(soap, &soap_tmp___ns3__bloqueEstadistica, "-ns3:bloqueEstadistica", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__bloqueEstadisticaResponse*>(&ns3__bloqueEstadisticaResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__bloqueEstadisticaResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__bloqueEstadisticaResponse_.soap_get(soap, "ns3:bloqueEstadisticaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::consultaCorreoPorNumeroCliente(const char *endpoint, const char *soap_action, ns3__consultaCorreoPorNumeroClienteRequest *ns3__consultaCorreoPorNumeroClienteRequest_, ns3__consultaCorreoPorNumeroClienteResponse &ns3__consultaCorreoPorNumeroClienteResponse_)
{	struct soap *soap = this;
	struct __ns3__consultaCorreoPorNumeroCliente soap_tmp___ns3__consultaCorreoPorNumeroCliente;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:ConsultaCorreoPorNumeroCliente";
	soap_tmp___ns3__consultaCorreoPorNumeroCliente.ns3__consultaCorreoPorNumeroClienteRequest_ = ns3__consultaCorreoPorNumeroClienteRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__consultaCorreoPorNumeroCliente(soap, &soap_tmp___ns3__consultaCorreoPorNumeroCliente);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__consultaCorreoPorNumeroCliente(soap, &soap_tmp___ns3__consultaCorreoPorNumeroCliente, "-ns3:consultaCorreoPorNumeroCliente", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__consultaCorreoPorNumeroCliente(soap, &soap_tmp___ns3__consultaCorreoPorNumeroCliente, "-ns3:consultaCorreoPorNumeroCliente", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__consultaCorreoPorNumeroClienteResponse*>(&ns3__consultaCorreoPorNumeroClienteResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__consultaCorreoPorNumeroClienteResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__consultaCorreoPorNumeroClienteResponse_.soap_get(soap, "ns3:consultaCorreoPorNumeroClienteResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::consultarIndicadoresPorCorreo(const char *endpoint, const char *soap_action, ns3__consultarIndicadoresPorCorreoRequest *ns3__consultarIndicadoresPorCorreoRequest_, ns3__consultarIndicadoresPorCorreoResponse &ns3__consultarIndicadoresPorCorreoResponse_)
{	struct soap *soap = this;
	struct __ns3__consultarIndicadoresPorCorreo soap_tmp___ns3__consultarIndicadoresPorCorreo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:ConsultarIndicadoresPorCorreo";
	soap_tmp___ns3__consultarIndicadoresPorCorreo.ns3__consultarIndicadoresPorCorreoRequest_ = ns3__consultarIndicadoresPorCorreoRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__consultarIndicadoresPorCorreo(soap, &soap_tmp___ns3__consultarIndicadoresPorCorreo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__consultarIndicadoresPorCorreo(soap, &soap_tmp___ns3__consultarIndicadoresPorCorreo, "-ns3:consultarIndicadoresPorCorreo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__consultarIndicadoresPorCorreo(soap, &soap_tmp___ns3__consultarIndicadoresPorCorreo, "-ns3:consultarIndicadoresPorCorreo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__consultarIndicadoresPorCorreoResponse*>(&ns3__consultarIndicadoresPorCorreoResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__consultarIndicadoresPorCorreoResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__consultarIndicadoresPorCorreoResponse_.soap_get(soap, "ns3:consultarIndicadoresPorCorreoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::consultarIndicadoresPorNumeroCliente(const char *endpoint, const char *soap_action, ns3__consultarIndicadoresPorNumeroClienteRequest *ns3__consultarIndicadoresPorNumeroClienteRequest_, ns3__consultarIndicadoresPorNumeroClienteResponse &ns3__consultarIndicadoresPorNumeroClienteResponse_)
{	struct soap *soap = this;
	struct __ns3__consultarIndicadoresPorNumeroCliente soap_tmp___ns3__consultarIndicadoresPorNumeroCliente;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:ConsultarIndicadoresPorNumeroCliente";
	soap_tmp___ns3__consultarIndicadoresPorNumeroCliente.ns3__consultarIndicadoresPorNumeroClienteRequest_ = ns3__consultarIndicadoresPorNumeroClienteRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__consultarIndicadoresPorNumeroCliente(soap, &soap_tmp___ns3__consultarIndicadoresPorNumeroCliente);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__consultarIndicadoresPorNumeroCliente(soap, &soap_tmp___ns3__consultarIndicadoresPorNumeroCliente, "-ns3:consultarIndicadoresPorNumeroCliente", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__consultarIndicadoresPorNumeroCliente(soap, &soap_tmp___ns3__consultarIndicadoresPorNumeroCliente, "-ns3:consultarIndicadoresPorNumeroCliente", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__consultarIndicadoresPorNumeroClienteResponse*>(&ns3__consultarIndicadoresPorNumeroClienteResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__consultarIndicadoresPorNumeroClienteResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__consultarIndicadoresPorNumeroClienteResponse_.soap_get(soap, "ns3:consultarIndicadoresPorNumeroClienteResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::cierreEstaditica(const char *endpoint, const char *soap_action, ns3__cierreEstadisticasRequest *ns3__cierreEstadisticasRequest_, ns3__cierreEstadisticasResponse &ns3__cierreEstadisticasResponse_)
{	struct soap *soap = this;
	struct __ns3__cierreEstaditica soap_tmp___ns3__cierreEstaditica;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:CierreEstaditica";
	soap_tmp___ns3__cierreEstaditica.ns3__cierreEstadisticasRequest_ = ns3__cierreEstadisticasRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__cierreEstaditica(soap, &soap_tmp___ns3__cierreEstaditica);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__cierreEstaditica(soap, &soap_tmp___ns3__cierreEstaditica, "-ns3:cierreEstaditica", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__cierreEstaditica(soap, &soap_tmp___ns3__cierreEstaditica, "-ns3:cierreEstaditica", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__cierreEstadisticasResponse*>(&ns3__cierreEstadisticasResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__cierreEstadisticasResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__cierreEstadisticasResponse_.soap_get(soap, "ns3:cierreEstadisticasResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy::insertaMovimientos(const char *endpoint, const char *soap_action, ns3__insertaMovimientosRequest *ns3__insertaMovimientosRequest_, ns3__insertaMovimientosResponse &ns3__insertaMovimientosResponse_)
{	struct soap *soap = this;
	struct __ns3__insertaMovimientos soap_tmp___ns3__insertaMovimientos;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.44.1.57:8081/EcommerceValidacionDeCorreosArg/services/EcommerceValidacionDeCorreosArg";
	if (soap_action == NULL)
		soap_action = "urn:InsertaMovimientos";
	soap_tmp___ns3__insertaMovimientos.ns3__insertaMovimientosRequest_ = ns3__insertaMovimientosRequest_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns3__insertaMovimientos(soap, &soap_tmp___ns3__insertaMovimientos);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__insertaMovimientos(soap, &soap_tmp___ns3__insertaMovimientos, "-ns3:insertaMovimientos", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__insertaMovimientos(soap, &soap_tmp___ns3__insertaMovimientos, "-ns3:insertaMovimientos", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns3__insertaMovimientosResponse*>(&ns3__insertaMovimientosResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns3__insertaMovimientosResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__insertaMovimientosResponse_.soap_get(soap, "ns3:insertaMovimientosResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
