/* soapautentificaHuellaProxy.h
   Generated by gSOAP 2.8.55 for ah.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapautentificaHuellaProxy_H
#define soapautentificaHuellaProxy_H
#include "soapH.h"

    class SOAP_CMAC autentificaHuellaProxy : public soap {
      public:
        /// Endpoint URL of service 'autentificaHuellaProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in ah.h, if any
        /// Construct a proxy with new managing context
        autentificaHuellaProxy();
        /// Copy constructor
        autentificaHuellaProxy(const autentificaHuellaProxy& rhs);
        /// Construct proxy given a managing context
        autentificaHuellaProxy(const struct soap&);
        /// Constructor taking an endpoint URL
        autentificaHuellaProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        autentificaHuellaProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        autentificaHuellaProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        autentificaHuellaProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~autentificaHuellaProxy();
        /// Initializer used by constructors
        virtual void autentificaHuellaProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual autentificaHuellaProxy *copy();
        /// Copy assignment
        autentificaHuellaProxy& operator=(const autentificaHuellaProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'ConsultaCliente' (returns SOAP_OK or error code)
        virtual int ConsultaCliente(ns2__entrada *entradaCliente, char *num_respuesta)
        { return this->ConsultaCliente(NULL, NULL, entradaCliente, num_respuesta); }
        virtual int ConsultaCliente(const char *soap_endpoint, const char *soap_action, ns2__entrada *entradaCliente, char *num_respuesta);
        /// Web service operation 'ConsultaEmpleado' (returns SOAP_OK or error code)
        virtual int ConsultaEmpleado(ns2__entrada *entradaEmpleado, char *num_respuesta)
        { return this->ConsultaEmpleado(NULL, NULL, entradaEmpleado, num_respuesta); }
        virtual int ConsultaEmpleado(const char *soap_endpoint, const char *soap_action, ns2__entrada *entradaEmpleado, char *num_respuesta);
        /// Web service operation 'Cliente' (returns SOAP_OK or error code)
        virtual int Cliente(ns2__entrada *entradaCliente, struct ns2__ClienteResponse &_param_1)
        { return this->Cliente(NULL, NULL, entradaCliente, _param_1); }
        virtual int Cliente(const char *soap_endpoint, const char *soap_action, ns2__entrada *entradaCliente, struct ns2__ClienteResponse &_param_1);
        /// Web service operation 'Empleado' (returns SOAP_OK or error code)
        virtual int Empleado(ns2__entrada *entradaEmpleado, struct ns2__EmpleadoResponse &_param_1)
        { return this->Empleado(NULL, NULL, entradaEmpleado, _param_1); }
        virtual int Empleado(const char *soap_endpoint, const char *soap_action, ns2__entrada *entradaEmpleado, struct ns2__EmpleadoResponse &_param_1);
    };
#endif
