/* soapEcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.55 for ah.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapEcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy_H
#define soapEcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy : public soap {
      public:
        /// Endpoint URL of service 'EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in ah.h, if any
        /// Construct a proxy with new managing context
        EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy();
        /// Copy constructor
        EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(const EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy& rhs);
        /// Construct proxy given a managing context
        EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(const struct soap&);
        /// Constructor taking an endpoint URL
        EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy();
        /// Initializer used by constructors
        virtual void EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy *copy();
        /// Copy assignment
        EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy& operator=(const EcommerceValidacionDeCorreosArgWebImplServiceSoapBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'validaSintaxisCorreo' (returns SOAP_OK or error code)
        virtual int validaSintaxisCorreo(ns3__validaSintaxisCorreoRequest *ns3__validaSintaxisCorreoRequest_, ns3__validaSintaxisCorreoResponse &ns3__validaSintaxisCorreoResponse_)
        { return this->validaSintaxisCorreo(NULL, NULL, ns3__validaSintaxisCorreoRequest_, ns3__validaSintaxisCorreoResponse_); }
        virtual int validaSintaxisCorreo(const char *soap_endpoint, const char *soap_action, ns3__validaSintaxisCorreoRequest *ns3__validaSintaxisCorreoRequest_, ns3__validaSintaxisCorreoResponse &ns3__validaSintaxisCorreoResponse_);
        /// Web service operation 'consultaCorreo' (returns SOAP_OK or error code)
        virtual int consultaCorreo(ns3__consultaCorreoRequest *ns3__consultaCorreoRequest_, ns3__consultaCorreoResponse &ns3__consultaCorreoResponse_)
        { return this->consultaCorreo(NULL, NULL, ns3__consultaCorreoRequest_, ns3__consultaCorreoResponse_); }
        virtual int consultaCorreo(const char *soap_endpoint, const char *soap_action, ns3__consultaCorreoRequest *ns3__consultaCorreoRequest_, ns3__consultaCorreoResponse &ns3__consultaCorreoResponse_);
        /// Web service operation 'validaCandidato' (returns SOAP_OK or error code)
        virtual int validaCandidato(ns3__validaCandidatoRequest *ns3__validaCandidatoRequest_, ns3__validaCandidatoResponse &ns3__validaCandidatoResponse_)
        { return this->validaCandidato(NULL, NULL, ns3__validaCandidatoRequest_, ns3__validaCandidatoResponse_); }
        virtual int validaCandidato(const char *soap_endpoint, const char *soap_action, ns3__validaCandidatoRequest *ns3__validaCandidatoRequest_, ns3__validaCandidatoResponse &ns3__validaCandidatoResponse_);
        /// Web service operation 'validarFrecuencia' (returns SOAP_OK or error code)
        virtual int validarFrecuencia(ns3__validarFrecuenciaRequest *ns3__validarFrecuenciaRequest_, ns3__validarFrecuenciaResponse &ns3__validarFrecuenciaResponse_)
        { return this->validarFrecuencia(NULL, NULL, ns3__validarFrecuenciaRequest_, ns3__validarFrecuenciaResponse_); }
        virtual int validarFrecuencia(const char *soap_endpoint, const char *soap_action, ns3__validarFrecuenciaRequest *ns3__validarFrecuenciaRequest_, ns3__validarFrecuenciaResponse &ns3__validarFrecuenciaResponse_);
        /// Web service operation 'desligueClienteCorreo' (returns SOAP_OK or error code)
        virtual int desligueClienteCorreo(ns3__desligueClienteCorreoRequest *ns3__desligueClienteCorreoRequest_, ns3__desliqueClienteCorreoResponse &ns3__desliqueClienteCorreoResponse_)
        { return this->desligueClienteCorreo(NULL, NULL, ns3__desligueClienteCorreoRequest_, ns3__desliqueClienteCorreoResponse_); }
        virtual int desligueClienteCorreo(const char *soap_endpoint, const char *soap_action, ns3__desligueClienteCorreoRequest *ns3__desligueClienteCorreoRequest_, ns3__desliqueClienteCorreoResponse &ns3__desliqueClienteCorreoResponse_);
        /// Web service operation 'desligueClienteNumeroCliente' (returns SOAP_OK or error code)
        virtual int desligueClienteNumeroCliente(ns3__desligueClienteNumeroClienteRequest *ns3__desligueClienteNumeroClienteRequest_, ns3__desliqueClienteNumeroClienteResponse &ns3__desliqueClienteNumeroClienteResponse_)
        { return this->desligueClienteNumeroCliente(NULL, NULL, ns3__desligueClienteNumeroClienteRequest_, ns3__desliqueClienteNumeroClienteResponse_); }
        virtual int desligueClienteNumeroCliente(const char *soap_endpoint, const char *soap_action, ns3__desligueClienteNumeroClienteRequest *ns3__desligueClienteNumeroClienteRequest_, ns3__desliqueClienteNumeroClienteResponse &ns3__desliqueClienteNumeroClienteResponse_);
        /// Web service operation 'registroCorreo' (returns SOAP_OK or error code)
        virtual int registroCorreo(ns3__registroCorreoRequest *ns3__registroCorreoRequest_, ns3__registroCorreoResponse &ns3__registroCorreoResponse_)
        { return this->registroCorreo(NULL, NULL, ns3__registroCorreoRequest_, ns3__registroCorreoResponse_); }
        virtual int registroCorreo(const char *soap_endpoint, const char *soap_action, ns3__registroCorreoRequest *ns3__registroCorreoRequest_, ns3__registroCorreoResponse &ns3__registroCorreoResponse_);
        /// Web service operation 'registroCorreoBancoppel' (returns SOAP_OK or error code)
        virtual int registroCorreoBancoppel(ns3__registroCorreoBancoppelRequest *ns3__registroCorreoBancoppelRequest_, ns3__registroCorreoBancoppelResponse &ns3__registroCorreoBancoppelResponse_)
        { return this->registroCorreoBancoppel(NULL, NULL, ns3__registroCorreoBancoppelRequest_, ns3__registroCorreoBancoppelResponse_); }
        virtual int registroCorreoBancoppel(const char *soap_endpoint, const char *soap_action, ns3__registroCorreoBancoppelRequest *ns3__registroCorreoBancoppelRequest_, ns3__registroCorreoBancoppelResponse &ns3__registroCorreoBancoppelResponse_);
        /// Web service operation 'bloqueEstadistica' (returns SOAP_OK or error code)
        virtual int bloqueEstadistica(ns3__bloqueEstadisticaRequest *ns3__bloqueEstadisticaRequest_, ns3__bloqueEstadisticaResponse &ns3__bloqueEstadisticaResponse_)
        { return this->bloqueEstadistica(NULL, NULL, ns3__bloqueEstadisticaRequest_, ns3__bloqueEstadisticaResponse_); }
        virtual int bloqueEstadistica(const char *soap_endpoint, const char *soap_action, ns3__bloqueEstadisticaRequest *ns3__bloqueEstadisticaRequest_, ns3__bloqueEstadisticaResponse &ns3__bloqueEstadisticaResponse_);
        /// Web service operation 'consultaCorreoPorNumeroCliente' (returns SOAP_OK or error code)
        virtual int consultaCorreoPorNumeroCliente(ns3__consultaCorreoPorNumeroClienteRequest *ns3__consultaCorreoPorNumeroClienteRequest_, ns3__consultaCorreoPorNumeroClienteResponse &ns3__consultaCorreoPorNumeroClienteResponse_)
        { return this->consultaCorreoPorNumeroCliente(NULL, NULL, ns3__consultaCorreoPorNumeroClienteRequest_, ns3__consultaCorreoPorNumeroClienteResponse_); }
        virtual int consultaCorreoPorNumeroCliente(const char *soap_endpoint, const char *soap_action, ns3__consultaCorreoPorNumeroClienteRequest *ns3__consultaCorreoPorNumeroClienteRequest_, ns3__consultaCorreoPorNumeroClienteResponse &ns3__consultaCorreoPorNumeroClienteResponse_);
        /// Web service operation 'consultarIndicadoresPorCorreo' (returns SOAP_OK or error code)
        virtual int consultarIndicadoresPorCorreo(ns3__consultarIndicadoresPorCorreoRequest *ns3__consultarIndicadoresPorCorreoRequest_, ns3__consultarIndicadoresPorCorreoResponse &ns3__consultarIndicadoresPorCorreoResponse_)
        { return this->consultarIndicadoresPorCorreo(NULL, NULL, ns3__consultarIndicadoresPorCorreoRequest_, ns3__consultarIndicadoresPorCorreoResponse_); }
        virtual int consultarIndicadoresPorCorreo(const char *soap_endpoint, const char *soap_action, ns3__consultarIndicadoresPorCorreoRequest *ns3__consultarIndicadoresPorCorreoRequest_, ns3__consultarIndicadoresPorCorreoResponse &ns3__consultarIndicadoresPorCorreoResponse_);
        /// Web service operation 'consultarIndicadoresPorNumeroCliente' (returns SOAP_OK or error code)
        virtual int consultarIndicadoresPorNumeroCliente(ns3__consultarIndicadoresPorNumeroClienteRequest *ns3__consultarIndicadoresPorNumeroClienteRequest_, ns3__consultarIndicadoresPorNumeroClienteResponse &ns3__consultarIndicadoresPorNumeroClienteResponse_)
        { return this->consultarIndicadoresPorNumeroCliente(NULL, NULL, ns3__consultarIndicadoresPorNumeroClienteRequest_, ns3__consultarIndicadoresPorNumeroClienteResponse_); }
        virtual int consultarIndicadoresPorNumeroCliente(const char *soap_endpoint, const char *soap_action, ns3__consultarIndicadoresPorNumeroClienteRequest *ns3__consultarIndicadoresPorNumeroClienteRequest_, ns3__consultarIndicadoresPorNumeroClienteResponse &ns3__consultarIndicadoresPorNumeroClienteResponse_);
        /// Web service operation 'cierreEstaditica' (returns SOAP_OK or error code)
        virtual int cierreEstaditica(ns3__cierreEstadisticasRequest *ns3__cierreEstadisticasRequest_, ns3__cierreEstadisticasResponse &ns3__cierreEstadisticasResponse_)
        { return this->cierreEstaditica(NULL, NULL, ns3__cierreEstadisticasRequest_, ns3__cierreEstadisticasResponse_); }
        virtual int cierreEstaditica(const char *soap_endpoint, const char *soap_action, ns3__cierreEstadisticasRequest *ns3__cierreEstadisticasRequest_, ns3__cierreEstadisticasResponse &ns3__cierreEstadisticasResponse_);
        /// Web service operation 'insertaMovimientos' (returns SOAP_OK or error code)
        virtual int insertaMovimientos(ns3__insertaMovimientosRequest *ns3__insertaMovimientosRequest_, ns3__insertaMovimientosResponse &ns3__insertaMovimientosResponse_)
        { return this->insertaMovimientos(NULL, NULL, ns3__insertaMovimientosRequest_, ns3__insertaMovimientosResponse_); }
        virtual int insertaMovimientos(const char *soap_endpoint, const char *soap_action, ns3__insertaMovimientosRequest *ns3__insertaMovimientosRequest_, ns3__insertaMovimientosResponse &ns3__insertaMovimientosResponse_);
    };
#endif
